// Copyright 2025 The go-wemix-wbft Authors
// This file is part of the go-wemix-wbft library.
//
// The go-wemix-wbft library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-wemix-wbft library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-wemix-wbft library. If not, see <http://www.gnu.org/licenses/>.
//
// This file is derived from quorum/consensus/istanbul/qbft/engine/engine_test.go (2024.07.25).
// Modified and improved for the wemix development.

package wbftengine

import (
	"bytes"
	"crypto/ecdsa"
	"errors"
	"math/big"
	"reflect"
	"slices"
	"strconv"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/consensus"
	"github.com/ethereum/go-ethereum/consensus/wbft"
	wbftcommon "github.com/ethereum/go-ethereum/consensus/wbft/common"
	wbftcore "github.com/ethereum/go-ethereum/consensus/wbft/core"
	"github.com/ethereum/go-ethereum/consensus/wbft/validator"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/core/state"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/crypto/bls"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/params"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/systemcontracts"
	"github.com/stretchr/testify/require"
)

// RLP data can be generated by using TestGeneratingGenesisExtra in testutils package
// Notice that default genesis extra data is used
//
//   go test -v -count 1 ./consensus/wbft/testutils -run TestGeneratingGenesisExtra

func TestPrepareExtra(t *testing.T) {
	expectedResult, _ := rlp.EncodeToBytes(
		&types.WBFTExtra{
			VanityData:        append([]byte{}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraVanity)...),
			PrevRound:         0,
			PrevPreparedSeal:  nil,
			PrevCommittedSeal: nil,
			Round:             0,
			PreparedSeal:      nil,
			CommittedSeal:     nil,
			GasTip:            big.NewInt(0),
			EpochInfo:         nil,
		},
	)

	h := &types.Header{}
	_, err := ApplyHeaderWBFTExtra(
		h,
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}
	if !reflect.DeepEqual(h.Extra, expectedResult) {
		t.Errorf("payload mismatch: have %v, want %v", hexutil.Encode(h.Extra), hexutil.Encode(expectedResult))
	}
}

var (
	testAccount1 = toTestAccount("0x2b3e3bef942608f06b249dc2d7e0847bda9708f3c82f3b57cd29419418553084")
	testAccount2 = toTestAccount("0xbb7d23e80e71e188af0243402c9fe20d677695e17c97418ab9d684cc0e022c4e")
	testAccount3 = toTestAccount("0x698d0f7ce7836c241f3ced2ff4d349e432ea470e75b2bba60224f7179ab45dd8")
	testAccount4 = toTestAccount("0x7e1e874b5fa7c4d09540e92b47206376abe6b3bebcbed3e48e74d680242e45a5")
)

func toTestAccount(prvKey string) account {
	key, _ := crypto.ToECDSA(hexutil.MustDecode(prvKey))
	blsKey, _ := bls.DeriveFromECDSA(key)
	addr := crypto.PubkeyToAddress(key.PublicKey)
	return account{key: key, blsKey: blsKey, addr: addr}
}

func TestWriteCommittedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf901a5808080c0c080c0f86301b860a7c28d1668faa74b00d7edb22fb059478b453064c892c6a5fe71063dbdf82b24d64e989a47f7e74274704723e1f163b10d2a32d600bef81b08694f6b75dd0586ed634248bbf16fb4081f847ba5d1ca90ad7a1898f60e46b45ba88c657e04342f80f90135f868d99438007fcf6b864660f6609a78b234c3ed2dda0165831cfde0d9942348a3100ba18e638b9fbdc71fc30a270da842fe831cfde0d994a2ae7388bbc7ba8cb7077d286a777ff944f75323831cfde0d9946726d67c31f91c8f2312f0d34edc71deb9478653831cfde0c480010203f8c4b0a22bf1dba4afc80a1783fb8f1870d1ff03e360284c2127db01abc0f5c4f810420968d5de337464d53dd926238c2984efb0b324470b778f2b89fee03494ba1e372916afd91d3711e99dd4bccab89b706ee814fbbf9770c14c31da1479beda9a054db0afd075d669527722dde94cb8664e54ae53becf8dd56801ec87c6893351a1691fabb9d2a39c6a864b903f10965bb16bafb08220645a1a3eebe953059de9164d9fec6c30c0dcd22d650f8de907d4c2cd74423312cdb56150019ede5ec1cec43bc8a1")
	expectedCommittedSeal := testAccount1.blsKey.Sign(append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)).Marshal()
	expectedIstExtra := &types.WBFTExtra{
		VanityData:        []byte{},
		RandaoReveal:      []byte{},
		PrevRound:         0,
		PrevCommittedSeal: nil,
		PrevPreparedSeal:  nil,
		Round:             0,
		CommittedSeal:     &types.WBFTAggregatedSeal{Signature: expectedCommittedSeal, Sealers: types.SealerSet{0x1}},
		PreparedSeal:      nil,
		GasTip:            big.NewInt(0),
		EpochInfo: &types.EpochInfo{
			Candidates: []*types.Candidate{
				{Addr: testAccount1.addr, Diligence: 1_900_000},
				{Addr: testAccount2.addr, Diligence: 1_900_000},
				{Addr: testAccount3.addr, Diligence: 1_900_000},
				{Addr: testAccount4.addr, Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
			BLSPublicKeys: [][]byte{
				testAccount1.blsKey.PublicKey().Marshal(),
				testAccount2.blsKey.PublicKey().Marshal(),
				testAccount3.blsKey.PublicKey().Marshal(),
				testAccount4.blsKey.PublicKey().Marshal(),
			},
		},
	}
	// use this to generate istRawData
	// encodedIstExtra, _ := rlp.EncodeToBytes(expectedIstExtra)
	// fmt.Printf("encodedIstExtra: %s\n", hexutil.Encode(encodedIstExtra))

	h := &types.Header{
		Extra: istRawData,
	}
	// normal case
	_, err := ApplyHeaderWBFTExtra(
		h,
		writeCommittedSeals([]wbft.SealData{{Seal: expectedCommittedSeal, Sealer: 0}}),
		WriteGasTip(big.NewInt(0)),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify wbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	_, err = ApplyHeaderWBFTExtra(
		h,
		writeCommittedSeals([]wbft.SealData{}),
	)
	if err != wbftcommon.ErrInvalidCommittedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, wbftcommon.ErrInvalidCommittedSeals)
	}

	unexpectedCommittedSeal := append(expectedCommittedSeal, make([]byte, 1)...)
	_, err = ApplyHeaderWBFTExtra(
		h,
		writeCommittedSeals([]wbft.SealData{{Seal: unexpectedCommittedSeal, Sealer: 0}}),
	)
	if err != wbftcommon.ErrInvalidSeal {
		t.Errorf("error mismatch: have %v, want %v", err, wbftcommon.ErrInvalidSeal)
	}
}

func TestWritePreparedSeals(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf901a5808080c0c080f86301b860a7c28d1668faa74b00d7edb22fb059478b453064c892c6a5fe71063dbdf82b24d64e989a47f7e74274704723e1f163b10d2a32d600bef81b08694f6b75dd0586ed634248bbf16fb4081f847ba5d1ca90ad7a1898f60e46b45ba88c657e04342fc080f90135f868d99438007fcf6b864660f6609a78b234c3ed2dda0165831cfde0d9942348a3100ba18e638b9fbdc71fc30a270da842fe831cfde0d994a2ae7388bbc7ba8cb7077d286a777ff944f75323831cfde0d9946726d67c31f91c8f2312f0d34edc71deb9478653831cfde0c480010203f8c4b0a22bf1dba4afc80a1783fb8f1870d1ff03e360284c2127db01abc0f5c4f810420968d5de337464d53dd926238c2984efb0b324470b778f2b89fee03494ba1e372916afd91d3711e99dd4bccab89b706ee814fbbf9770c14c31da1479beda9a054db0afd075d669527722dde94cb8664e54ae53becf8dd56801ec87c6893351a1691fabb9d2a39c6a864b903f10965bb16bafb08220645a1a3eebe953059de9164d9fec6c30c0dcd22d650f8de907d4c2cd74423312cdb56150019ede5ec1cec43bc8a1")
	expectedPreparedSeal := testAccount1.blsKey.Sign(append([]byte{1, 2, 3}, bytes.Repeat([]byte{0x00}, types.IstanbulExtraSeal-3)...)).Marshal()
	expectedIstExtra := &types.WBFTExtra{
		VanityData:        []byte{},
		RandaoReveal:      []byte{},
		PrevRound:         0,
		PrevCommittedSeal: nil,
		PrevPreparedSeal:  nil,
		Round:             0,
		CommittedSeal:     nil,
		PreparedSeal:      &types.WBFTAggregatedSeal{Signature: expectedPreparedSeal, Sealers: types.SealerSet{0x1}},
		GasTip:            big.NewInt(0),
		EpochInfo: &types.EpochInfo{
			Candidates: []*types.Candidate{
				{Addr: testAccount1.addr, Diligence: 1_900_000},
				{Addr: testAccount2.addr, Diligence: 1_900_000},
				{Addr: testAccount3.addr, Diligence: 1_900_000},
				{Addr: testAccount4.addr, Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
			BLSPublicKeys: [][]byte{
				testAccount1.blsKey.PublicKey().Marshal(),
				testAccount2.blsKey.PublicKey().Marshal(),
				testAccount3.blsKey.PublicKey().Marshal(),
				testAccount4.blsKey.PublicKey().Marshal(),
			},
		},
	}
	// use this to generate istRawData
	// encodedIstExtra, _ := rlp.EncodeToBytes(expectedIstExtra)
	// fmt.Printf("TestWritePreparedSeals encodedIstExtra: %s\n", hexutil.Encode(encodedIstExtra))

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	_, err := ApplyHeaderWBFTExtra(
		h,
		writePreparedSeals([]wbft.SealData{{Seal: expectedPreparedSeal, Sealer: 0}}),
	)
	if err != nil {
		t.Errorf("error mismatch: have %v, want: nil", err)
	}

	// verify wbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra, expectedIstExtra)
	}

	// invalid seal
	_, err = ApplyHeaderWBFTExtra(
		h,
		writePreparedSeals([]wbft.SealData{}),
	)
	if err != wbftcommon.ErrInvalidPreparedSeals {
		t.Errorf("error mismatch: have %v, want %v", err, wbftcommon.ErrInvalidPreparedSeals)
	}

	unexpectedPreparedSeal := append(expectedPreparedSeal, make([]byte, 1)...)
	_, err = ApplyHeaderWBFTExtra(
		h,
		writePreparedSeals([]wbft.SealData{{Seal: unexpectedPreparedSeal, Sealer: 0}}),
	)
	if err != wbftcommon.ErrInvalidSeal {
		t.Errorf("error mismatch: have %v, want %v", err, wbftcommon.ErrInvalidSeal)
	}
}

func TestWriteRoundNumber(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf90141808080c0c080c0c080f90135f868d99438007fcf6b864660f6609a78b234c3ed2dda0165831cfde0d9942348a3100ba18e638b9fbdc71fc30a270da842fe831cfde0d994a2ae7388bbc7ba8cb7077d286a777ff944f75323831cfde0d9946726d67c31f91c8f2312f0d34edc71deb9478653831cfde0c480010203f8c4b0a22bf1dba4afc80a1783fb8f1870d1ff03e360284c2127db01abc0f5c4f810420968d5de337464d53dd926238c2984efb0b324470b778f2b89fee03494ba1e372916afd91d3711e99dd4bccab89b706ee814fbbf9770c14c31da1479beda9a054db0afd075d669527722dde94cb8664e54ae53becf8dd56801ec87c6893351a1691fabb9d2a39c6a864b903f10965bb16bafb08220645a1a3eebe953059de9164d9fec6c30c0dcd22d650f8de907d4c2cd74423312cdb56150019ede5ec1cec43bc8a1")
	expectedIstExtra := &types.WBFTExtra{
		VanityData:        []byte{},
		RandaoReveal:      []byte{},
		PrevRound:         0,
		PrevCommittedSeal: nil,
		PrevPreparedSeal:  nil,
		Round:             0,
		CommittedSeal:     nil,
		PreparedSeal:      nil,
		GasTip:            big.NewInt(0),
		EpochInfo: &types.EpochInfo{
			Candidates: []*types.Candidate{
				{Addr: testAccount1.addr, Diligence: 1_900_000},
				{Addr: testAccount2.addr, Diligence: 1_900_000},
				{Addr: testAccount3.addr, Diligence: 1_900_000},
				{Addr: testAccount4.addr, Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
			BLSPublicKeys: [][]byte{
				testAccount1.blsKey.PublicKey().Marshal(),
				testAccount2.blsKey.PublicKey().Marshal(),
				testAccount3.blsKey.PublicKey().Marshal(),
				testAccount4.blsKey.PublicKey().Marshal(),
			},
		},
	}
	// use this to generate istRawData
	// encodedIstExtra, _ := rlp.EncodeToBytes(expectedIstExtra)
	// fmt.Printf("TestWriteRoundNumber encodedIstExtra: %s\n", hexutil.Encode(encodedIstExtra))

	var expectedErr error

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	_, err := ApplyHeaderWBFTExtra(
		h,
		writeRoundNumber(big.NewInt(5)),
	)
	if err != expectedErr {
		t.Errorf("error mismatch: have %v, want %v", err, expectedErr)
	}

	// verify wbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if istExtra.Round != 5 {
		t.Errorf("writing round does not effected")
	}
	istExtra.Round = expectedIstExtra.Round
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra.VanityData, expectedIstExtra.VanityData)
	}
}

func TestWriteGasTip(t *testing.T) {
	istRawData := hexutil.MustDecode("0xf90141808080c0c080c0c080f90135f868d99438007fcf6b864660f6609a78b234c3ed2dda0165831cfde0d9942348a3100ba18e638b9fbdc71fc30a270da842fe831cfde0d994a2ae7388bbc7ba8cb7077d286a777ff944f75323831cfde0d9946726d67c31f91c8f2312f0d34edc71deb9478653831cfde0c480010203f8c4b0a22bf1dba4afc80a1783fb8f1870d1ff03e360284c2127db01abc0f5c4f810420968d5de337464d53dd926238c2984efb0b324470b778f2b89fee03494ba1e372916afd91d3711e99dd4bccab89b706ee814fbbf9770c14c31da1479beda9a054db0afd075d669527722dde94cb8664e54ae53becf8dd56801ec87c6893351a1691fabb9d2a39c6a864b903f10965bb16bafb08220645a1a3eebe953059de9164d9fec6c30c0dcd22d650f8de907d4c2cd74423312cdb56150019ede5ec1cec43bc8a1")
	expectedIstExtra := &types.WBFTExtra{
		VanityData:        []byte{},
		RandaoReveal:      []byte{},
		PrevRound:         0,
		PrevCommittedSeal: nil,
		PrevPreparedSeal:  nil,
		Round:             0,
		CommittedSeal:     nil,
		PreparedSeal:      nil,
		GasTip:            big.NewInt(0),
		EpochInfo: &types.EpochInfo{
			Candidates: []*types.Candidate{
				{Addr: testAccount1.addr, Diligence: 1_900_000},
				{Addr: testAccount2.addr, Diligence: 1_900_000},
				{Addr: testAccount3.addr, Diligence: 1_900_000},
				{Addr: testAccount4.addr, Diligence: 1_900_000},
			},
			Validators: []uint32{0, 1, 2, 3},
			BLSPublicKeys: [][]byte{
				testAccount1.blsKey.PublicKey().Marshal(),
				testAccount2.blsKey.PublicKey().Marshal(),
				testAccount3.blsKey.PublicKey().Marshal(),
				testAccount4.blsKey.PublicKey().Marshal(),
			},
		},
	}
	// use this to generate istRawData
	// encodedIstExtra, _ := rlp.EncodeToBytes(expectedIstExtra)
	// fmt.Printf("TestWriteRoundNumber encodedIstExtra: %s\n", hexutil.Encode(encodedIstExtra))

	var expectedErr error

	h := &types.Header{
		Extra: istRawData,
	}

	// normal case
	_, err := ApplyHeaderWBFTExtra(
		h,
		WriteGasTip(big.NewInt(int64(params.InitialGasTip))),
	)
	if err != expectedErr {
		t.Errorf("error mismatch: have %v, want %v", err, expectedErr)
	}

	// verify wbft extra-data
	istExtra, err := getExtra(h)
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	if istExtra.GasTip.Cmp(big.NewInt(int64(params.InitialGasTip))) != 0 {
		t.Errorf("writing gas tip does not effected")
	}
	istExtra.GasTip = expectedIstExtra.GasTip
	if !reflect.DeepEqual(istExtra, expectedIstExtra) {
		t.Errorf("extra data mismatch: have %v, want %v", istExtra.VanityData, expectedIstExtra.VanityData)
	}
}

func TestSortCandidates(t *testing.T) {
	candidates := []PoweredCandidate{
		{Addr: common.HexToAddress("0x1"), Power: new(big.Int).SetUint64(10001), Diligence: 100},
		{Addr: common.HexToAddress("0x2"), Power: new(big.Int).SetUint64(10001), Diligence: 101},
		{Addr: common.HexToAddress("0x3"), Power: new(big.Int).SetUint64(10002), Diligence: 102},
		{Addr: common.HexToAddress("0x4"), Power: new(big.Int).SetUint64(10002), Diligence: 103},
		{Addr: common.HexToAddress("0x5"), Power: new(big.Int).SetUint64(10000), Diligence: 104},
		{Addr: common.HexToAddress("0x6"), Power: new(big.Int).SetUint64(10000), Diligence: 105},
	}
	expected := []PoweredCandidate{
		{Addr: common.HexToAddress("0x4"), Power: new(big.Int).SetUint64(10002), Diligence: 103},
		{Addr: common.HexToAddress("0x3"), Power: new(big.Int).SetUint64(10002), Diligence: 102},
		{Addr: common.HexToAddress("0x2"), Power: new(big.Int).SetUint64(10001), Diligence: 101},
		{Addr: common.HexToAddress("0x1"), Power: new(big.Int).SetUint64(10001), Diligence: 100},
		{Addr: common.HexToAddress("0x6"), Power: new(big.Int).SetUint64(10000), Diligence: 105},
		{Addr: common.HexToAddress("0x5"), Power: new(big.Int).SetUint64(10000), Diligence: 104},
	}
	results := sortCandidates(candidates)
	if len(results) != len(expected) {
		t.Fatalf("expected %d candidates, got %d", len(expected), len(results))
	}
	for i, result := range results {
		if candidates[result].Addr != expected[i].Addr {
			t.Errorf("candidate %d address mismatch: have %s, want %s", i, candidates[result].Addr.Hex(), expected[i].Addr.Hex())
		}
	}
}

func TestWriteRandao(t *testing.T) {
	privateKey, _ := crypto.GenerateKey()
	blockNumber := big.NewInt(3)
	parentMixDigest := crypto.Keccak256Hash([]byte("My sample randao mix"))
	engine := NewEngine(wbft.DefaultConfig, crypto.PubkeyToAddress(privateKey.PublicKey), func(data []byte) ([]byte, error) {
		hashData := crypto.Keccak256(data)
		return crypto.Sign(hashData, privateKey)
	}, nil)

	chainConfig := &params.ChainConfig{
		ChainID: new(big.Int).SetUint64(9999),
	}

	expectedRandaoReveal, _ := crypto.Sign(crypto.Keccak256(makeRandaoData(chainConfig, blockNumber)), privateKey)
	randaoRevealHash := crypto.Keccak256Hash(expectedRandaoReveal)
	bigA := new(big.Int).SetBytes(parentMixDigest.Bytes())
	bigB := new(big.Int).SetBytes(randaoRevealHash.Bytes())
	resultBigInt := new(big.Int).Xor(bigA, bigB)
	expectedRandaoMix := common.BigToHash(resultBigInt)

	expectedIstExtra := &types.WBFTExtra{
		VanityData:        []byte{},
		RandaoReveal:      expectedRandaoReveal,
		PrevRound:         0,
		PrevCommittedSeal: nil,
		PrevPreparedSeal:  nil,
		Round:             0,
		CommittedSeal:     nil,
		PreparedSeal:      nil,
		EpochInfo:         nil,
	}
	header := &types.Header{
		Number: blockNumber,
	}

	istExtra, err := ApplyHeaderWBFTExtra(header, engine.WriteRandao(chainConfig, header))
	if err != nil {
		t.Errorf("error mismatch: have %v, want nil", err)
	}
	resultMixDigest := CalculateRandaoMix(parentMixDigest, istExtra.RandaoReveal)
	if resultMixDigest.Cmp(expectedRandaoMix) != 0 {
		t.Errorf("extra RandaoMix mismatch: have %v, want %v", resultMixDigest, expectedRandaoMix)
	}
	if !bytes.Equal(istExtra.RandaoReveal, expectedIstExtra.RandaoReveal) {
		t.Errorf("extra RandaoReveal mismatch: have %v, want %v", istExtra.RandaoReveal, expectedIstExtra.RandaoReveal)
	}
}

type fakeChain struct {
	chainConfig *params.ChainConfig
	headers     []*types.Header
	statedb     *state.StateDB
}

var _ consensus.ChainHeaderReader = (*fakeChain)(nil)

func (f *fakeChain) Config() *params.ChainConfig {
	return f.chainConfig
}
func (f *fakeChain) CurrentHeader() *types.Header { return nil }
func (f *fakeChain) GetHeader(hash common.Hash, number uint64) *types.Header {
	return f.headers[number]
}
func (f *fakeChain) GetHeaderByNumber(number uint64) *types.Header    { return nil }
func (f *fakeChain) GetHeaderByHash(hash common.Hash) *types.Header   { return nil }
func (f *fakeChain) GetTd(hash common.Hash, number uint64) *big.Int   { return nil }
func (f *fakeChain) StateAt(root common.Hash) (*state.StateDB, error) { return f.statedb, nil }

func (f *fakeChain) insertHeader(h *types.Header) {
	f.headers = append(f.headers, h)
}

type account struct {
	key    *ecdsa.PrivateKey
	addr   common.Address
	blsKey bls.SecretKey
}

func newAccounts(n int) (accounts []account) {
	for i := 0; i < n; i++ {
		key, _ := crypto.GenerateKey()
		blsKey, _ := bls.DeriveFromECDSA(key)
		addr := crypto.PubkeyToAddress(key.PublicKey)
		accounts = append(accounts, account{key: key, blsKey: blsKey, addr: addr})
	}

	return accounts
}

func updateChainConfig(chainConfig *params.ChainConfig, newValidators []account) {
	vals := ""
	blsKeys := ""
	for i, v := range newValidators {
		if i != 0 {
			vals += ","
			blsKeys += ","
		}
		vals += v.addr.Hex()
		blsKeys += "0x" + hexutil.Encode(v.blsKey.PublicKey().Marshal())[2:]
	}
	chainConfig.Anzeon.SystemContracts.GovValidator.Params[systemcontracts.GOV_BASE_PARAM_MEMBERS] = vals
	chainConfig.Anzeon.SystemContracts.GovValidator.Params[systemcontracts.GOV_BASE_PARAM_QUORUM] = strconv.Itoa(len(newValidators))
	chainConfig.Anzeon.SystemContracts.GovValidator.Params[systemcontracts.GOV_VALIDATOR_PARAM_VALIDATORS] = vals
	chainConfig.Anzeon.SystemContracts.GovValidator.Params[systemcontracts.GOV_VALIDATOR_PARAM_BLS_KEYS] = blsKeys
}

func TestEpochInfo(t *testing.T) {
	var testCases = []struct {
		name           string
		totValidators  int
		proposers      []int
		preparedSeals  [][]int
		committedSeals [][]int
		expDiligences  [][]uint64
	}{
		{
			"All validators include seals completely (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{ // first block should not include seals
				{}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{}, {0, 1, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1906666, 1906666, 1906666},
				{1906666, 1906666, 1906666}, {1906666, 1906666, 1906666}, {1915999, 1915999, 1915999},
			},
		},
		{
			"Some validators miss seals for other validators (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{}, {0, 1}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1906666, 1884444, 1873333},
				{1906666, 1884444, 1873333}, {1906666, 1884444, 1873333}, {1915999, 1895999, 1885999},
			},
		},
		{
			"Some validators miss own seals (3 validators, 3 blocks / epoch)",
			3,
			[]int{0, 1, 2, 0, 1, 2},
			[][]int{
				{}, {0, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{}, {0, 2}, {0, 1, 2},
				{0, 1, 2}, {0, 1, 2}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1906666, 1851111, 1906666},
				{1906666, 1851111, 1906666}, {1906666, 1851111, 1906666}, {1915999, 1865999, 1882666},
			},
		},
		{
			"Validators propose multiple number of blocks (2 validators, 3 blocks / epoch)",
			2,
			[]int{0, 1, 0, 1, 0, 1},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]int{
				{0, 1}, {0, 1}, {0, 1},
				{0, 1}, {0, 1}, {0, 1},
			},
			[][]uint64{
				{1900000, 1900000}, {1900000, 1900000}, {1906666, 1906666},
				{1906666, 1906666}, {1906666, 1906666}, {1915999, 1915999},
			},
		},
		{
			"Some validators are excluded from proposing blocks (4 validators, 3 blocks / epoch)",
			4,
			[]int{0, 1, 2, 3, 0, 1},
			[][]int{
				{}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]int{
				{}, {0, 1, 2, 3}, {0, 1, 2, 3},
				{0, 1, 2, 3}, {0, 1, 2, 3}, {0, 1, 2, 3},
			},
			[][]uint64{
				{1900000, 1900000, 1900000, 1900000}, {1900000, 1900000, 1900000, 1900000}, {1906666, 1906666, 1906666, 1906666},
				{1906666, 1906666, 1906666, 1906666}, {1906666, 1906666, 1906666, 1906666}, {1915999, 1915999, 1915999, 1915999},
			},
		},
		{
			"Round changes occur (3 validators, 3 blocks / epoch)",
			3,
			[]int{2, 1, 0, 2, 1, 1}, // 0, 1, "2", 0, "1", 2, "0", 1, "2", 0, "1", 2, 0, "1"
			[][]int{
				{}, {0, 1, 2}, {0, 1, 2},
				{}, {0, 1, 2}, {0, 1, 2},
			},
			[][]int{
				{}, {0, 1, 2}, {0, 1, 2},
				{}, {0, 1, 2}, {0, 1, 2},
			},
			[][]uint64{
				{1900000, 1900000, 1900000}, {1900000, 1900000, 1900000}, {1862222, 1873333, 1840000},
				{1862222, 1873333, 1840000}, {1862222, 1873333, 1840000}, {1742666, 1819332, 1722666},
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var parent *types.Header

			// Setup signers
			signers := newAccounts(tc.totValidators)

			// Setup test chain genesis
			c := new(fakeChain)
			c.chainConfig = params.TestWBFTChainConfig
			updateChainConfig(c.chainConfig, signers)

			wbftCfg := new(wbft.Config)
			wbft.SetConfigFromChainConfig(wbftCfg, c.chainConfig)
			wbftCfg.Epoch = 3

			engine := NewEngine(wbftCfg, common.Address{}, nil, nil)
			parent = makeGenesis(signers)
			c.insertHeader(parent)

			db := rawdb.NewMemoryDatabase()
			tdb := state.NewDatabase(db)
			statedb, _ := state.New(types.EmptyRootHash, tdb, nil)

			st, _ := wbft.GetSystemContractsStateTransition(wbftCfg, parent.Number)
			for _, c := range st.Codes {
				statedb.SetCode(c.Address, hexutil.MustDecode(c.Code))
			}
			for _, s := range st.States {
				statedb.SetState(s.Address, s.Key, s.Value)
			}

			sequentialProposerIndex := uint32(0)
			// Finalize and insert blocks based according to test case
			for i, author := range tc.proposers {
				var preparedSealDatas, committedSealDatas []wbft.SealData
				var preparedSeal, committedSeal *types.WBFTAggregatedSeal

				h := makeHeader(parent)
				h.Coinbase = signers[author].addr

				// Fill prev seals
				round := uint32((i + 1) % 4) // deterministic random round
				for _, s := range tc.preparedSeals[i] {
					preparedSealDatas = append(preparedSealDatas, makeSeal(parent, s, signers[s], round, wbftcore.SealTypePrepare))
				}
				for _, s := range tc.committedSeals[i] {
					committedSealDatas = append(committedSealDatas, makeSeal(parent, s, signers[s], round, wbftcore.SealTypeCommit))
				}
				preparedSeal, _ = aggregateSeal(preparedSealDatas)
				committedSeal, _ = aggregateSeal(committedSealDatas)
				ApplyHeaderWBFTExtra(
					h,
					WritePrevSeals(round, preparedSeal, committedSeal),
				)

				// Build epoch info
				newEpoch, _ := engine.buildEpochInfo(c, h, statedb)
				if newEpoch != nil {
					// manipulate validators to make sequential proposer order(to ignore random proposer selection)
					for i := 0; i < len(newEpoch.Validators); i++ {
						newEpoch.Validators[i] = sequentialProposerIndex
						sequentialProposerIndex = (sequentialProposerIndex + 1) % uint32(len(tc.proposers))
					}
				}
				ApplyHeaderWBFTExtra(h, WriteEpochInfo(newEpoch))
				isEpoch, _, _ := engine.IsEpochBlockNumber(c.chainConfig, h.Number)
				if newEpoch != nil && !isEpoch {
					t.Errorf("expected epoch info to be nil")
				}

				c.insertHeader(h)
				parent = h

				// Get nearest epoch block
				var eb *types.Header
				if newEpoch != nil {
					eb = h
				} else {
					eb = getEpochBlock(engine, c, h)
				}
				wbftExtra, _ := types.ExtractWBFTExtra(eb)

				// Validate diligences
				for j, d := range tc.expDiligences[i] {
					candi := wbftExtra.EpochInfo.Candidates[j]
					if d != candi.Diligence {
						t.Errorf("expected diligence mismatch for candidate %d: have %d, want %d", j, candi.Diligence, d)
					}
				}
			}
		})
	}
}

func makeGenesis(signers []account) *types.Header {
	header := &types.Header{
		Number:     big.NewInt(0),
		Time:       uint64(time.Now().UnixNano()),
		Difficulty: types.WBFTDefaultDifficulty,
	}

	e := new(types.EpochInfo)
	for i, s := range signers {
		e.Candidates = append(e.Candidates, &types.Candidate{Addr: s.addr, Diligence: 1900000})
		e.Validators = append(e.Validators, uint32(i))
		e.BLSPublicKeys = append(e.BLSPublicKeys, s.blsKey.PublicKey().Marshal())
	}
	ApplyHeaderWBFTExtra(header, WriteEpochInfo(e))
	return header
}

func makeHeader(parent *types.Header) *types.Header {
	header := types.CopyHeader(parent)
	header.Number.Add(header.Number, big.NewInt(1))
	header.Time = uint64(time.Now().UnixNano())

	return header
}

func makeSeal(h *types.Header, index int, node account, round uint32, sealType wbftcore.SealType) wbft.SealData {
	return wbft.SealData{
		Seal:   node.blsKey.Sign(wbftcore.PrepareSeal(h, round, sealType)).Marshal(),
		Sealer: uint32(index),
	}
}

func getEpochBlock(e *Engine, chain consensus.ChainHeaderReader, header *types.Header) *types.Header {
	config := chain.Config()
	for {
		header = chain.GetHeader(header.ParentHash, header.Number.Uint64()-1)
		if isEpoch, _, err := e.IsEpochBlockNumber(config, header.Number); err != nil {
			log.Crit("IsEpochBlockNumber failed", "number", header.Number, "err", err)
		} else if isEpoch {
			break
		}
	}

	return header
}

func TestIsEpochBlock(t *testing.T) {
	engine := NewEngine(nil, common.Address{}, nil, nil)

	testCases := []struct {
		name                string
		chainConfig         params.ChainConfig
		config              wbft.Config
		blockNumber         *big.Int
		expectedResult      bool
		expectedLatestEpoch *big.Int
		expectedError       error
	}{
		// case 1: zero block is an epoch block
		{
			"zero block is an epoch block",
			params.ChainConfig{
				Anzeon: params.DefaultAnzeonConfig,
			},
			wbft.Config{
				Epoch: 100,
			},
			new(big.Int),
			true,
			new(big.Int),
			nil,
		},
		// case 2: 1 block is not an epoch block
		{
			"1 block is not an epoch block",
			params.ChainConfig{
				Anzeon: params.DefaultAnzeonConfig,
			},
			wbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(1),
			false,
			new(big.Int),
			nil,
		},
		// case 3: epoch - 1 block is not an epoch block
		{
			"epoch - 1 block is not an epoch block",
			params.ChainConfig{
				Anzeon: params.DefaultAnzeonConfig,
			},
			wbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(99),
			false,
			new(big.Int),
			nil,
		},
		// case 4: epoch block is an epoch block
		{
			"epoch block is an epoch block",
			params.ChainConfig{
				Anzeon: params.DefaultAnzeonConfig,
			},
			wbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(100),
			true,
			new(big.Int).SetUint64(100),
			nil,
		},
		// case 5: epoch block * n is an epoch block
		{
			"epoch block * n is an epoch block",
			params.ChainConfig{
				Anzeon: params.DefaultAnzeonConfig,
			},
			wbft.Config{
				Epoch: 100,
			},
			new(big.Int).SetUint64(300),
			true,
			new(big.Int).SetUint64(300),
			nil,
		},
	}

	for _, tc := range testCases {
		testConfig := tc.config
		engine.cfg = &testConfig
		if r, epoch, err := engine.IsEpochBlockNumber(&tc.chainConfig, tc.blockNumber); err != nil {
			if !errors.Is(err, tc.expectedError) {
				t.Errorf("[%s] unexpected error: have %v, want %v", tc.name, err, tc.expectedError)
			}
			if epoch != nil {
				t.Errorf("[%s] unexpected epoch: have %v, want nil", tc.name, epoch)
			}
		} else {
			if r != tc.expectedResult {
				t.Errorf("[%s] unexpected result: have %v, want %v", tc.name, r, tc.expectedResult)
			}
			if epoch.Cmp(tc.expectedLatestEpoch) != 0 {
				t.Errorf("[%s] unexpected epoch: have %v, want %v", tc.name, epoch, tc.expectedLatestEpoch)
			}
		}
	}
}

func TestComputeShuffledIndex(t *testing.T) {
	sampleSeed := crypto.Keccak256Hash([]byte("sample seed for testing"))
	result1 := make([]uint64, 0)
	result2 := make([]uint64, 0)
	for i := 0; i < 10; i++ {
		result, err := computeShuffledIndex(uint64(i), uint64(10), sampleSeed, true)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		for _, h := range result1 {
			if result == h {
				t.Errorf("duplicate index found: %d", result)
			}
		}
		result1 = append(result1, result)
	}
	for i := 0; i < 10; i++ {
		result, err := computeShuffledIndex(uint64(i), uint64(10), sampleSeed, true)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		result2 = append(result2, result)
	}
	if !slices.Equal(result1, result2) {
		t.Errorf("expected results to be equal, but got different results: %v and %v", result1, result2)
	}
}

func TestBlacklistedSigner(t *testing.T) {
	signer := testAccount1

	tests := []struct {
		name            string
		parentExists    bool
		blacklisted     bool
		expectErr       error
		errContainsPart string
	}{
		{
			name:         "missing parent header",
			parentExists: false,
			blacklisted:  false,
			expectErr:    consensus.ErrUnknownAncestor,
		},
		{
			name:         "not blacklisted signer",
			parentExists: true,
			blacklisted:  false,
			expectErr:    nil,
		},
		{
			name:            "blacklisted signer",
			parentExists:    true,
			blacklisted:     true,
			expectErr:       wbftcommon.ErrBlacklistedSigner,
			errContainsPart: signer.addr.Hex(),
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			var parent *types.Header
			if tc.parentExists {
				parent = &types.Header{
					Number: big.NewInt(1),
					Root:   common.Hash{},
				}
			}

			mockState, _ := state.New(types.EmptyRootHash, state.NewDatabase(rawdb.NewMemoryDatabase()), nil)
			mockState.CreateAccount(signer.addr)
			if tc.blacklisted {
				mockState.SetBlacklisted(signer.addr)
			}

			fc := &fakeChain{
				chainConfig: params.TestWBFTChainConfig,
				headers:     []*types.Header{nil, parent},
				statedb:     mockState,
			}

			engine := NewEngine(nil, common.Address{}, nil, nil)

			header := &types.Header{
				Number:     big.NewInt(2),
				ParentHash: common.HexToHash("0x1"),
				Coinbase:   signer.addr,
			}

			addrs := []common.Address{
				signer.addr,
			}
			blsPubKeys := [][]byte{
				signer.blsKey.PublicKey().Marshal(),
			}
			validators := validator.NewSet(addrs, blsPubKeys, wbft.NewRoundRobinProposerPolicy())

			err := engine.verifySigner(fc, header, parent, validators)

			if tc.expectErr == nil {
				require.NoError(t, err)
			} else {
				require.ErrorIs(t, err, tc.expectErr)
				if tc.errContainsPart != "" {
					require.Contains(t, err.Error(), tc.errContainsPart)
				}
			}
		})
	}
}
